[plugins]
arduino-cli = "https://github.com/egnor/asdf-arduino-cli.git"

[tools]
arduino-cli = {version = "1.0.2"}
python = {version = "3.11", virtualenv = "dev.tmp/python_venv"}

[settings]
experimental = true
python_compile = false
python_venv_auto_create = true

[env]
ARDUINO_BOARD_MANAGER_ADDITIONAL_URLS = "https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_dev_index.json"
ARDUINO_DIRECTORIES_DATA = "{{config_root}}/dev.tmp/arduino"
ARDUINO_LIBRARY_ENABLE_UNSAFE_INSTALL = "true"
